use studentdata;

CREATE TABLE STUDENTINFO(
   EN_NO   INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(20) NOT NULL,
   UNIVERSITY VARCHAR(30) NOT NULL,
   CGPA DOUBLE NOT NULL,
   PRIMARY KEY (EN_NO)
);

CREATE TABLE STUDENTRESULT(
   SID   INT NOT NULL,
   MARKS INT NOT NULL,
   YEAR  INT NOT NULL
);